language: csharp
os: linux
dist: xenial
sudo: true
mono: none
dotnet: 3.1.1

branches:
    only: 
        - master
        - /.*/
before_script:
    - chmod -R a+x scripts

install:
- dotnet restore

script:
- dotnet build