language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 3.1.101
branches:
    only: 
        - master
        - /.*/
before_script:
    - chmod _R a+x scripts
script:
    - ./scripts/travis-build.sh
after_success:
    - ./scripts/travis-success.sh
notification:
    email:
        on_success: never
        on_failer: always