language: csharp
dist: xenial
mono: none
dotnet: 3.1.1
branches:
    only: 
        - master
        - /.*/
before_script:
    - chmod -R a+x scripts
script:
    - ./scripts/travis-build.sh
after_success:
    - ./scripts/travis-success.sh
notifications:
    email:
        on_success: never
        on_faileur: always